### PR TITLE
[#159469906] refactor slack incidence report

### PR DESCRIPTION
**Pull request by egichuri**

### CODE REVIEW

**Comment by egichuri** [comment]
@precious-ijege - trying this out to see if it'll speed up the slack command. lemme know what you think

**Comment by precious-ijege** [comment]
@egichuri I see you reduced the number of interactions with the user. Good move! Looks good. We can test the branch locally to find out.

**Comment by egichuri** [comment]
I tested it and it seems to work fine..

**Comment by precious-ijege** [comment]
Ok! How about testing? Then we can merge it and try it out on production.

**Pull request merged**
