### PR TITLE
[#156224169] Add custom authentication for API requests

### PR DESCRIPTION
**Pull request by iankigen**
#### What does this PR do?

Allow users to use token based authentication with google

#### Description of Task to be completed?

- add custom login api view
- implement custom login in tests

#### How should this be manually tested?

`python manage.py test`

Using postman `Authorization: ` `Token {your_token}`

#### What are the relevant pivotal tracker stories?

[#156224169](https://www.pivotaltracker.com/n/projects/2146417/stories/156224169)

#### Screenshots 
authenticated

### CODE REVIEW

**Comment by iankigen** [comment]
@egichuri @alexkiura @nelmandela Kindly review

**Comment by iankigen** [comment]
@egichuri @alexkiura @nelmandela Kindly review

**Comment by iankigen** [comment]
@egichuri @alexkiura @HawiCaesar @nelmandela Kindly review

**Comment by nelmandela** [comment]
LGTM

**Comment by HawiCaesar** [comment]
LGTM

**Pull request merged**
