### PR TITLE
#158555572 Allow pagination on API endpoints

### PR DESCRIPTION
**Pull request by QUDUSKUNLE**
### What does this PR do?
- It allows pagination on API endpoints

### Description of Task to be completed?
- Add pagination method to app settings
- Ensure no test is broken

#### How should this be manually tested?
- Hit any of the endpoints

### Screenshot
screen shot 2018-06-29 at 6 36 47 pm
screen shot 2018-06-29 at 6 38 29 pm

### CODE REVIEW

**Comment by collinmutembei** [comment]
@QUDUSKUNLE Have you come across this warning when running tests
<details>
  <summary>UnorderedObjectListWarning</summary>
  
  ```shell
  → pmt                                                                                                                                                                                                                                                             [3b62927]
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
./Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AllocationHistory'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
.../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.Asset'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
.................../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetCategory'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
....../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetCondition'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
................/Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetIncidentReport'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
...................../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetLog'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
.............../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetMake'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
....../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetModelNumber'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
............../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetStatus'>
QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
.../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetSubCategory'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
........../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.asset.AssetType'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
...../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.user.SecurityUser'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
.............../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.user.User'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
................../Users/houdini/Projects/.envs/art-backend-WK13VbPm/lib/python3.6/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.user.UserFeedback'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
..............................................................
----------------------------------------------------------------------
Ran 214 tests in 17.408s

OK
Destroying test database for alias 'default'...
  ```
  
 </details>

Could you look into resolving it; to be on the safe side. See [this](https://goo.gl/ib8yTZ).

**Comment by egichuri** [comment]
I think we can order by id (if i got what you meant)

**Comment by collinmutembei** [comment]
@egichuri Ascending or Descending? See the link I have shared with @QUDUSKUNLE above.

**Comment by egichuri** [comment]
let's do descending

**Comment by collinmutembei** [comment]
Awesome @QUDUSKUNLE!

**Pull request merged**
