### PR TITLE
[#162780375]: Filter verified/unverified assets

### PR DESCRIPTION
**Pull request by nelmandela**
### What does PR do?

	•Allows filtering of verified and unverified assets

### Description of task to be completed:

	•Add verified/unverified filter on the AssetFilter class

### How can it be tested manually?

	•Navigate to assets endpoint and try out filtering either by verified or unverified

### Related pivotal tracker stories

	•[#162780375](https://www.pivotaltracker.com/story/show/162780375)

### Screenshots:

screen shot 2019-01-17 at 19 30 58

screen shot 2019-01-17 at 19 30 24

### CODE REVIEW

**Comment by egichuri** [comment]
@nelmandela could you update the screenshots to show the `verified` value?

**Comment by nelmandela** [comment]
@egichuri a little help here,i don't really understand what you mean by that

**Comment by egichuri** [comment]
From the screenshots you can't tell whether the assets returned are verified or not, since the values shown cut off at `allocation_history`. i've tested it manually though, you can go ahead and merge

**Comment by nelmandela** [comment]
@egichuri advisement on how to proceed here

**Pull request merged**
